;Windless Bay for Amiga OCS - (c) RESISTANCE.NO 2021
;THIS SHELL SCRIPT WAS GENERATED BY R-PAGE RESOURCE TOOLCHAIN
;DON'T MODIFY IT !

failat 21

;create the assets folder on each disk

makedir "wind1:assets"

;update each file

;txt_dialog_fr.pak -> DATA_DISK_0
echo "updating (txt_dialog_fr.pak)"
delete "wind1:assets/txt_dialog_fr.pak"
copy "txt_dialog_fr.pak" "wind1:assets/txt_dialog_fr.pak"

;txt_system_fr.pak -> DATA_DISK_0
echo "updating (txt_system_fr.pak)"
delete "wind1:assets/txt_system_fr.pak"
copy "txt_system_fr.pak" "wind1:assets/txt_system_fr.pak"

;txt_tooltip_fr.pak -> DATA_DISK_0
echo "updating (txt_tooltip_fr.pak)"
delete "wind1:assets/txt_tooltip_fr.pak"
copy "txt_tooltip_fr.pak" "wind1:assets/txt_tooltip_fr.pak"

;txt_credits_fr.pak -> DATA_DISK_0
echo "updating (txt_credits_fr.pak)"
delete "wind1:assets/txt_credits_fr.pak"
copy "txt_credits_fr.pak" "wind1:assets/txt_credits_fr.pak"

;txt_dialog_en.pak -> DATA_DISK_0
echo "updating (txt_dialog_en.pak)"
delete "wind1:assets/txt_dialog_en.pak"
copy "txt_dialog_en.pak" "wind1:assets/txt_dialog_en.pak"

;txt_system_en.pak -> DATA_DISK_0
echo "updating (txt_system_en.pak)"
delete "wind1:assets/txt_system_en.pak"
copy "txt_system_en.pak" "wind1:assets/txt_system_en.pak"

;txt_tooltip_en.pak -> DATA_DISK_0
echo "updating (txt_tooltip_en.pak)"
delete "wind1:assets/txt_tooltip_en.pak"
copy "txt_tooltip_en.pak" "wind1:assets/txt_tooltip_en.pak"

;txt_credits_en.pak -> DATA_DISK_0
echo "updating (txt_credits_en.pak)"
delete "wind1:assets/txt_credits_en.pak"
copy "txt_credits_en.pak" "wind1:assets/txt_credits_en.pak"

;txt_dialog_es.pak -> DATA_DISK_0
echo "updating (txt_dialog_es.pak)"
delete "wind1:assets/txt_dialog_es.pak"
copy "txt_dialog_es.pak" "wind1:assets/txt_dialog_es.pak"

;txt_system_es.pak -> DATA_DISK_0
echo "updating (txt_system_es.pak)"
delete "wind1:assets/txt_system_es.pak"
copy "txt_system_es.pak" "wind1:assets/txt_system_es.pak"

;txt_tooltip_es.pak -> DATA_DISK_0
echo "updating (txt_tooltip_es.pak)"
delete "wind1:assets/txt_tooltip_es.pak"
copy "txt_tooltip_es.pak" "wind1:assets/txt_tooltip_es.pak"

;txt_credits_es.pak -> DATA_DISK_0
echo "updating (txt_credits_es.pak)"
delete "wind1:assets/txt_credits_es.pak"
copy "txt_credits_es.pak" "wind1:assets/txt_credits_es.pak"

;gui.pak -> DATA_DISK_0
echo "updating (gui.pak)"
delete "wind1:assets/gui.pak"
copy "gui.pak" "wind1:assets/gui.pak"

;gui_compass_hilite.pak -> DATA_DISK_0
echo "updating (gui_compass_hilite.pak)"
delete "wind1:assets/gui_compass_hilite.pak"
copy "gui_compass_hilite.pak" "wind1:assets/gui_compass_hilite.pak"

;gui_compass_hilite_mask.pak -> DATA_DISK_0
echo "updating (gui_compass_hilite_mask.pak)"
delete "wind1:assets/gui_compass_hilite_mask.pak"
copy "gui_compass_hilite_mask.pak" "wind1:assets/gui_compass_hilite_mask.pak"

;icons.pak -> DATA_DISK_0
echo "updating (icons.pak)"
delete "wind1:assets/icons.pak"
copy "icons.pak" "wind1:assets/icons.pak"

;inventory_panel.pak -> DATA_DISK_0
echo "updating (inventory_panel.pak)"
delete "wind1:assets/inventory_panel.pak"
copy "inventory_panel.pak" "wind1:assets/inventory_panel.pak"

;travel_menu.pak -> DATA_DISK_0
echo "updating (travel_menu.pak)"
delete "wind1:assets/travel_menu.pak"
copy "travel_menu.pak" "wind1:assets/travel_menu.pak"

;spr_inventory.pak -> DATA_DISK_0
echo "updating (spr_inventory.pak)"
delete "wind1:assets/spr_inventory.pak"
copy "spr_inventory.pak" "wind1:assets/spr_inventory.pak"

;spr_inventory_mask.pak -> DATA_DISK_0
echo "updating (spr_inventory_mask.pak)"
delete "wind1:assets/spr_inventory_mask.pak"
copy "spr_inventory_mask.pak" "wind1:assets/spr_inventory_mask.pak"

;vue_01.pak -> DATA_DISK_0
echo "updating (vue_01.pak)"
delete "wind1:assets/vue_01.pak"
copy "vue_01.pak" "wind1:assets/vue_01.pak"

;vue_02.pak -> DATA_DISK_0
echo "updating (vue_02.pak)"
delete "wind1:assets/vue_02.pak"
copy "vue_02.pak" "wind1:assets/vue_02.pak"

;vue_03.pak -> DATA_DISK_0
echo "updating (vue_03.pak)"
delete "wind1:assets/vue_03.pak"
copy "vue_03.pak" "wind1:assets/vue_03.pak"

;vue_04.pak -> DATA_DISK_0
echo "updating (vue_04.pak)"
delete "wind1:assets/vue_04.pak"
copy "vue_04.pak" "wind1:assets/vue_04.pak"

;vue_05.pak -> DATA_DISK_0
echo "updating (vue_05.pak)"
delete "wind1:assets/vue_05.pak"
copy "vue_05.pak" "wind1:assets/vue_05.pak"

;vue_06.pak -> DATA_DISK_0
echo "updating (vue_06.pak)"
delete "wind1:assets/vue_06.pak"
copy "vue_06.pak" "wind1:assets/vue_06.pak"

;vue_07.pak -> DATA_DISK_0
echo "updating (vue_07.pak)"
delete "wind1:assets/vue_07.pak"
copy "vue_07.pak" "wind1:assets/vue_07.pak"

;vue_08.pak -> DATA_DISK_0
echo "updating (vue_08.pak)"
delete "wind1:assets/vue_08.pak"
copy "vue_08.pak" "wind1:assets/vue_08.pak"

;vue_09.pak -> DATA_DISK_0
echo "updating (vue_09.pak)"
delete "wind1:assets/vue_09.pak"
copy "vue_09.pak" "wind1:assets/vue_09.pak"

;vue_10.pak -> DATA_DISK_0
echo "updating (vue_10.pak)"
delete "wind1:assets/vue_10.pak"
copy "vue_10.pak" "wind1:assets/vue_10.pak"

;vue_11.pak -> DATA_DISK_0
echo "updating (vue_11.pak)"
delete "wind1:assets/vue_11.pak"
copy "vue_11.pak" "wind1:assets/vue_11.pak"

;vue_12.pak -> DATA_DISK_0
echo "updating (vue_12.pak)"
delete "wind1:assets/vue_12.pak"
copy "vue_12.pak" "wind1:assets/vue_12.pak"

;vue_13.pak -> DATA_DISK_0
echo "updating (vue_13.pak)"
delete "wind1:assets/vue_13.pak"
copy "vue_13.pak" "wind1:assets/vue_13.pak"

;vue_14.pak -> DATA_DISK_0
echo "updating (vue_14.pak)"
delete "wind1:assets/vue_14.pak"
copy "vue_14.pak" "wind1:assets/vue_14.pak"

;vue_15.pak -> DATA_DISK_0
echo "updating (vue_15.pak)"
delete "wind1:assets/vue_15.pak"
copy "vue_15.pak" "wind1:assets/vue_15.pak"

;vue_16.pak -> DATA_DISK_0
echo "updating (vue_16.pak)"
delete "wind1:assets/vue_16.pak"
copy "vue_16.pak" "wind1:assets/vue_16.pak"

;vue_17.pak -> DATA_DISK_0
echo "updating (vue_17.pak)"
delete "wind1:assets/vue_17.pak"
copy "vue_17.pak" "wind1:assets/vue_17.pak"

;vue_18.pak -> DATA_DISK_0
echo "updating (vue_18.pak)"
delete "wind1:assets/vue_18.pak"
copy "vue_18.pak" "wind1:assets/vue_18.pak"

;vue_19.pak -> DATA_DISK_0
echo "updating (vue_19.pak)"
delete "wind1:assets/vue_19.pak"
copy "vue_19.pak" "wind1:assets/vue_19.pak"
