/* Athanor2 (C) Eric "Atlantis" Safar / Safargames 2021 */
/* THIS CODE WAS GENERATED BY R-PAGE SCENARIO TOOLCHAIN */
/*                   DON'T MODIFY IT !                  */

#include <stdarg.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "rpage/frwk.h"
#include "game/text.h"
#include "game/world.h"
#include "game/special.h"

short current_room = 2;
short previous_vue = -1;
short current_world = world_iceland;

#ifdef DEBUG_MACROS
const char *game_object_name[MAX_GAME_OBJECTS] = {"VIDE", "CABLE", "COMBINE", 
	"TELEPHONE"};
#endif

const unsigned short game_object_crc16[MAX_GAME_OBJECTS] = {
	0x8f7, 0xc49f, 0xac05, 
	0x7163};

/* Combined objects */
combined_game_object combined_go[MAX_COMBINED_OBJECTS] = {
/* 	{ { go_A, go_B }, go_C },
	      A  +  B  -->  C
*/
	{ {go_CABLE, go_COMBINE}, go_TELEPHONE }
};

/****************************/
/* Sprites sheets per world */
/****************************/
const char *world_sprites_name[2] =
{
	"spr_blank", "spr_iceland"
};

sheet_sprite world_sprites[3] = 
{
	/* Sprite sheet for 'cnossos' */
	{
		/* go_CABLE*/
		{0, 0, 31, 109},
		{54, 31},
		1,
		FALSE,
		FALSE, /* default value */
		go_CABLE
	},
	{
		/* go_COMBINE*/
		{32, 0, 95, 94},
		{80, 50},
		2,
		FALSE,
		FALSE, /* default value */
		go_COMBINE
	},
	{
		/* go_TELEPHONE*/
		{96, 0, 127, 39},
		{132, 102},
		2,
		FALSE,
		FALSE, /* default value */
		go_TELEPHONE
	},
};


/*************************************/
/* Game Object to Sheet Sprite table */
/*************************************/
const short go_to_sprite[4] = 
{
	-1,
	0, /* go_CABLE */
	1, /* go_COMBINE */
	2, /* go_TELEPHONE */
};

/****************************************/
/* Game Object to Inventory Sprite Index*/
/****************************************/
const short go_to_inventory_sprite[4] = 
{
	-1,
	-1,
	-1,
	-1,
};
/****************************************/
/* Game Object to Inventory Tooltip Index*/
/****************************************/
const short go_to_inventory_tooltip[MAX_GAME_OBJECTS] = 
{
	-1, 
	-1, 
	-1, 
	-1, 
};

/***********/
/* Samples */
/***********/
sample_per_world world_samples[SAMPLE_WORLD_LEN] =
{
	{ world_iceland, 1, 0 }, /* mouette2 */
};


/************************/
/* Vue/Samples relation */
/************************/
sample_per_vue vue_samples[SAMPLE_VUES_LEN] =
{
	{ 1, 1}, /* vue 1, sample #1 */ 
};

/*********************/
/* Samples filenames */
/*********************/
char *sample_names[SAMPLE_NAMES_LEN] =
{
	"sfx_mouette2",
};

/********************************/
/* Portraits sprites definition */
/********************************/
const char *portrait_sprites[MAX_SPR_PORTRAITS] = 
{
	"npc_colonel_10",
	"npc_robot_10",
};

/******************/
/* Scenario flags */
/******************/

short Flag001, Flag002, Flag003, Flag004, Flag005, Flag006, Flag007, Flag009, Flag011, Flag012, Flag014, Flag015, Flag017, Flag018, Flag019, Flag020, Flag021, Flag022, Flag023, Flag024, Flag028, Flag029, Flag030, Flag031, Flag032, Flag034, Flag036, Flag037, Flag038, Flag039, Flag040, Flag041, Flag042, Flag068, Flag069;

/**************************/
/* SafarScript Conditions */
/**************************/

/* Master conditions */
void condition_master(void)
{
	switch(world_get_current_index())
	{
		case world_iceland: /* (CHAP1.CON, iceland) */
			if (Flag069 == 0)
			{
				game_load_music(mus_ville10b);
			}
			break; /* End of CHAP1.CON */

	}
}

/* Timers conditions */
void condition_timers(void)
{
	switch(world_get_current_index())
	{
		case world_iceland: /* (CHAP1.CON, iceland) */
			if (((Timer1 > 1000) && (Flag038 == 1)))
			{
				game_display_dialog(4);
				game_enable_timer1(OFF);
				game_over(1);
				return;
			}
			if (((Timer2 > 2500) && (Flag004 == 2)))
			{
				Flag004=4;
				game_enable_timer2(OFF);
			}
			break; /* End of CHAP1.CON */

	}
}

/* Vue conditions */
/* vue 1 */
BOOL conditions_vue_1(BOOL init_vue, short click_zone, short click_spr)
{
	/* vue-specific condition (CHAP1.CON) */
#ifdef DEBUG_MACROS
	if(click_zone > -1)
		printf("conditions for vue #1, zone = %d/%s, spr = %d\n", click_zone, game_object_name[click_zone], click_spr);
	else
		printf("conditions for vue #1, zone = %d, spr = %d\n", click_zone, click_spr);
#endif
	if (((click_zone == go_CABLE) && (game_is_current_action(act_look))))
	{
		game_play_sample(1);
		return TRUE;
	}
	return FALSE;
}


/***********/
/*  Zones  */
/***********/

zone zones[MAX_ZONE] = {
	/* { zone rect, object enum index, object variable pointer, condition code functer }*/
	{{{52, 85}, {96, 85}, {96, 122}, {52, 122}}, go_CABLE, &conditions_vue_1}, 		/* zone #0 */
};

/***********/
/*  Rooms  */
/***********/

room rooms[MAX_ROOM] = {
	{ /*    VUE_01    */
		1,
		"vue_01",
		{-1,1,2,-1},	/* east:VUE_02,south:VUE_03, */
		{0,-1,-1,-1,-1,-1,-1,-1},	/* CABLE,,,,,,,, */
		&conditions_vue_1
	},

	{ /*    VUE_02    */
		2,
		"vue_02",
		{-1,-1,-1,0},	/* west:VUE_01, */
		{-1,-1,-1,-1,-1,-1,-1,-1},	/* ,,,,,,,, */
		NULL
	},

	{ /*    VUE_03    */
		3,
		"vue_03",
		{3,-1,0,-1},	/* north:VUE_04,south:VUE_01, */
		{-1,-1,-1,-1,-1,-1,-1,-1},	/* ,,,,,,,, */
		NULL
	},

	{ /*    VUE_04    */
		4,
		"vue_04",
		{5,-1,2,4},	/* north:VUE_06,south:VUE_03,west:VUE_05, */
		{-1,-1,-1,-1,-1,-1,-1,-1},	/* ,,,,,,,, */
		NULL
	},

	{ /*    VUE_05    */
		5,
		"vue_05",
		{-1,3,-1,-1},	/* east:VUE_04, */
		{-1,-1,-1,-1,-1,-1,-1,-1},	/* ,,,,,,,, */
		NULL
	},

	{ /*    VUE_06    */
		6,
		"vue_06",
		{6,-1,3,-1},	/* north:VUE_07,south:VUE_04, */
		{-1,-1,-1,-1,-1,-1,-1,-1},	/* ,,,,,,,, */
		NULL
	},

	{ /*    VUE_07    */
		7,
		"vue_07",
		{5,7,-1,-1},	/* north:VUE_06,east:VUE_08, */
		{-1,-1,-1,-1,-1,-1,-1,-1},	/* ,,,,,,,, */
		NULL
	},

	{ /*    VUE_08    */
		8,
		"vue_08",
		{9,8,-1,6},	/* north:VUE_10,east:VUE_09,west:VUE_07, */
		{-1,-1,-1,-1,-1,-1,-1,-1},	/* ,,,,,,,, */
		NULL
	},

	{ /*    VUE_09    */
		9,
		"vue_09",
		{-1,11,-1,7},	/* east:VUE_12,west:VUE_08, */
		{-1,-1,-1,-1,-1,-1,-1,-1},	/* ,,,,,,,, */
		NULL
	},

	{ /*    VUE_10    */
		10,
		"vue_10",
		{7,-1,10,-1},	/* north:VUE_08,south:VUE_11, */
		{-1,-1,-1,-1,-1,-1,-1,-1},	/* ,,,,,,,, */
		NULL
	},

	{ /*    VUE_11    */
		11,
		"vue_11",
		{9,-1,-1,-1},	/* north:VUE_10, */
		{-1,-1,-1,-1,-1,-1,-1,-1},	/* ,,,,,,,, */
		NULL
	},

	{ /*    VUE_12    */
		12,
		"vue_12",
		{12,-1,13,-1},	/* north:VUE_13,south:VUE_14, */
		{-1,-1,-1,-1,-1,-1,-1,-1},	/* ,,,,,,,, */
		NULL
	},

	{ /*    VUE_13    */
		13,
		"vue_13",
		{-1,-1,11,-1},	/* south:VUE_12, */
		{-1,-1,-1,-1,-1,-1,-1,-1},	/* ,,,,,,,, */
		NULL
	},

	{ /*    VUE_14    */
		14,
		"vue_14",
		{11,14,-1,-1},	/* north:VUE_12,east:VUE_15, */
		{-1,-1,-1,-1,-1,-1,-1,-1},	/* ,,,,,,,, */
		NULL
	},

	{ /*    VUE_15    */
		15,
		"vue_15",
		{-1,15,-1,13},	/* east:VUE_16,west:VUE_14, */
		{-1,-1,-1,-1,-1,-1,-1,-1},	/* ,,,,,,,, */
		NULL
	},

	{ /*    VUE_16    */
		16,
		"vue_16",
		{16,-1,-1,14},	/* north:VUE_17,west:VUE_15, */
		{-1,-1,-1,-1,-1,-1,-1,-1},	/* ,,,,,,,, */
		NULL
	},

	{ /*    VUE_17    */
		17,
		"vue_17",
		{-1,17,15,-1},	/* east:VUE_18,south:VUE_16, */
		{-1,-1,-1,-1,-1,-1,-1,-1},	/* ,,,,,,,, */
		NULL
	},

	{ /*    VUE_18    */
		18,
		"vue_18",
		{18,-1,-1,16},	/* north:VUE_19,west:VUE_17, */
		{-1,-1,-1,-1,-1,-1,-1,-1},	/* ,,,,,,,, */
		NULL
	},

	{ /*    VUE_19    */
		19,
		"vue_19",
		{-1,-1,17,-1},	/* south:VUE_18, */
		{-1,-1,-1,-1,-1,-1,-1,-1},	/* ,,,,,,,, */
		NULL
	},

	/* End of rooms list */
};


/* Various accessors */
short worldGetMaxRoom(void) { return MAX_ROOM; }
short worldGetCurrentRoom(void) { return current_room; }
void worldSetCurrentRoom(short room_index) { current_room = room_index; }
void worldSetCurrentRoomByVue(short vue_index) { 
	short i;
	for(i = 0; i < MAX_ROOM; i++)
	{
		if (rooms[i].vue_index == vue_index)
		{
			current_room = i;
			break;
		}
	}
}

void worldSetCurrentRoomByVue_ex(short vue_index, short dialog_index) {
	game_set_next_vue_dialog(dialog_index);
	worldSetCurrentRoomByVue(vue_index);
}

short vue_get_room_index(short vue_index) { 
	short i;
	for(i = 0; i < MAX_ROOM; i++)
	{
		if (rooms[i].vue_index == vue_index)
			return i;
	}
}

short roomGetVueIndex(short room_index) { return rooms[room_index].vue_index; }
short roomGetLinkDirection(short room_index, short dir) { return rooms[room_index].links[dir]; }

void worldSetCurrentChapter(short chapter_index) { /* stub function */ }
void world_set_current_index(short world_index) { current_world = world_index; }
short world_get_current_index(void) { return current_world; }
#ifdef DEBUG_MACROS
char *world_get_object_name(short object_index) { return game_object_name[object_index]; }
#endif

short getPreviousVue(void)
{
	return previous_vue;
}

void setPreviousVue(short v)
{
	previous_vue = v;
}

short worldGetMaxSheetSprites(void) { return 3;}

void worldOpenExitNorth(short from_index, short to_index)
{
	rooms[vue_get_room_index(from_index)].links[dir_north] = vue_get_room_index(to_index);
	game_vue_make_dirty();
}

void worldOpenExitSouth(short from_index, short to_index)
{
	rooms[vue_get_room_index(from_index)].links[dir_south] = vue_get_room_index(to_index);
	game_vue_make_dirty();
}

void worldOpenExitEast(short from_index, short to_index)
{
	rooms[vue_get_room_index(from_index)].links[dir_east] = vue_get_room_index(to_index);
	game_vue_make_dirty();
}

void worldOpenExitWest(short from_index, short to_index)
{
	rooms[vue_get_room_index(from_index)].links[dir_west] = vue_get_room_index(to_index);
	game_vue_make_dirty();
}

void worldCloseExitNorth(short vue_index)
{
	rooms[vue_get_room_index(vue_index)].links[dir_north] = -1;
	game_vue_make_dirty();
}

void worldCloseExitSouth(short vue_index)
{
	rooms[vue_get_room_index(vue_index)].links[dir_south] = -1;
	game_vue_make_dirty();
}

void worldCloseExitEast(short vue_index)
{
	rooms[vue_get_room_index(vue_index)].links[dir_east] = -1;
	game_vue_make_dirty();
}

void worldCloseExitWest(short vue_index)
{
	rooms[vue_get_room_index(vue_index)].links[dir_west] = -1;
	game_vue_make_dirty();
}

void worldClearScenarioFlags(void)
{
	Flag001 = 0;
	Flag002 = 0;
	Flag003 = 0;
	Flag004 = 0;
	Flag005 = 0;
	Flag006 = 0;
	Flag007 = 0;
	Flag009 = 1;
	Flag011 = 0;
	Flag012 = 0;
	Flag014 = 0;
	Flag015 = 0;
	Flag017 = 0;
	Flag018 = 0;
	Flag019 = 0;
	Flag020 = 0;
	Flag021 = 0;
	Flag022 = 0;
	Flag023 = 0;
	Flag024 = 0;
	Flag028 = 0;
	Flag029 = 0;
	Flag030 = 0;
	Flag031 = 0;
	Flag032 = 0;
	Flag034 = 0;
	Flag036 = 0;
	Flag037 = 0;
	Flag038 = 0;
	Flag039 = 0;
	Flag040 = 0;
	Flag041 = 0;
	Flag042 = 0;
	Flag068 = 1;
	Flag069 = 0;
}

void worldDebugScenarioFlags(char *_str)
{
	sprintf(_str, "Flag01=%d Flag02=%d Flag03=%d Flag04=%d\nFlag05=%d Flag06=%d Flag07=%d Flag09=%d\nFlag11=%d Flag12=%d Flag14=%d Flag15=%d\nFlag17=%d Flag18=%d Flag19=%d Flag20=%d\nFlag21=%d Flag22=%d Flag23=%d Flag24=%d\nFlag28=%d Flag29=%d Flag30=%d Flag31=%d\nFlag32=%d Flag34=%d Flag36=%d Flag37=%d\nFlag38=%d Flag39=%d Flag40=%d Flag41=%d\nFlag42=%d Flag68=%d Flag69=%d ", Flag001, Flag002, Flag003, Flag004, Flag005, Flag006, Flag007, Flag009, Flag011, Flag012, Flag014, Flag015, Flag017, Flag018, Flag019, Flag020, Flag021, Flag022, Flag023, Flag024, Flag028, Flag029, Flag030, Flag031, Flag032, Flag034, Flag036, Flag037, Flag038, Flag039, Flag040, Flag041, Flag042, Flag068, Flag069);
}

void gameObjectGetSpriteSheetCoords(short go_idx, rect *source, vec2 *dest)
{
	memcpy(source, &(world_sprites[go_to_sprite[go_idx]].source), sizeof(rect));
	memcpy(dest, &(world_sprites[go_to_sprite[go_idx]].dest), sizeof(vec2));
}

short gameObjectGetSpriteInventoryIndex(short go_idx)
{
	return go_to_inventory_sprite[go_idx];
}

short getSpriteSheetVueIndex(short idx)
{
	return world_sprites[idx].vue;
}

BOOL getSpriteSheetEnabled(short idx)
{
	return world_sprites[idx].enabled;
}

void setSpriteSheetEnabled(short idx, BOOL state)
{
	world_sprites[idx].enabled = state;
}

short getSpriteSheetGameObjectIndex(short idx)
{
	return world_sprites[idx].go_index;
}
short worldGetGameObjectFromCRC16(unsigned short value)
{
    short i;
    for(i = 0; i < MAX_GAME_OBJECTS; i++)
        if (game_object_crc16[i] == value)
            return i;

    return OBJECT_NONE;
}

void worldSaveScenarioFlags(rpage_file file)
{
	USHORT flag_idx;
	char *file_header = SAVE_HEADER_FLAGS;

	rpage_file_write(file, file_header, 4);
	flag_idx = 1;
	rpage_file_write(file, &flag_idx, 2);
	rpage_file_write(file, &Flag001, 2);
	flag_idx = 2;
	rpage_file_write(file, &flag_idx, 2);
	rpage_file_write(file, &Flag002, 2);
	flag_idx = 3;
	rpage_file_write(file, &flag_idx, 2);
	rpage_file_write(file, &Flag003, 2);
	flag_idx = 4;
	rpage_file_write(file, &flag_idx, 2);
	rpage_file_write(file, &Flag004, 2);
	flag_idx = 5;
	rpage_file_write(file, &flag_idx, 2);
	rpage_file_write(file, &Flag005, 2);
	flag_idx = 6;
	rpage_file_write(file, &flag_idx, 2);
	rpage_file_write(file, &Flag006, 2);
	flag_idx = 7;
	rpage_file_write(file, &flag_idx, 2);
	rpage_file_write(file, &Flag007, 2);
	flag_idx = 9;
	rpage_file_write(file, &flag_idx, 2);
	rpage_file_write(file, &Flag009, 2);
	flag_idx = 11;
	rpage_file_write(file, &flag_idx, 2);
	rpage_file_write(file, &Flag011, 2);
	flag_idx = 12;
	rpage_file_write(file, &flag_idx, 2);
	rpage_file_write(file, &Flag012, 2);
	flag_idx = 14;
	rpage_file_write(file, &flag_idx, 2);
	rpage_file_write(file, &Flag014, 2);
	flag_idx = 15;
	rpage_file_write(file, &flag_idx, 2);
	rpage_file_write(file, &Flag015, 2);
	flag_idx = 17;
	rpage_file_write(file, &flag_idx, 2);
	rpage_file_write(file, &Flag017, 2);
	flag_idx = 18;
	rpage_file_write(file, &flag_idx, 2);
	rpage_file_write(file, &Flag018, 2);
	flag_idx = 19;
	rpage_file_write(file, &flag_idx, 2);
	rpage_file_write(file, &Flag019, 2);
	flag_idx = 20;
	rpage_file_write(file, &flag_idx, 2);
	rpage_file_write(file, &Flag020, 2);
	flag_idx = 21;
	rpage_file_write(file, &flag_idx, 2);
	rpage_file_write(file, &Flag021, 2);
	flag_idx = 22;
	rpage_file_write(file, &flag_idx, 2);
	rpage_file_write(file, &Flag022, 2);
	flag_idx = 23;
	rpage_file_write(file, &flag_idx, 2);
	rpage_file_write(file, &Flag023, 2);
	flag_idx = 24;
	rpage_file_write(file, &flag_idx, 2);
	rpage_file_write(file, &Flag024, 2);
	flag_idx = 28;
	rpage_file_write(file, &flag_idx, 2);
	rpage_file_write(file, &Flag028, 2);
	flag_idx = 29;
	rpage_file_write(file, &flag_idx, 2);
	rpage_file_write(file, &Flag029, 2);
	flag_idx = 30;
	rpage_file_write(file, &flag_idx, 2);
	rpage_file_write(file, &Flag030, 2);
	flag_idx = 31;
	rpage_file_write(file, &flag_idx, 2);
	rpage_file_write(file, &Flag031, 2);
	flag_idx = 32;
	rpage_file_write(file, &flag_idx, 2);
	rpage_file_write(file, &Flag032, 2);
	flag_idx = 34;
	rpage_file_write(file, &flag_idx, 2);
	rpage_file_write(file, &Flag034, 2);
	flag_idx = 36;
	rpage_file_write(file, &flag_idx, 2);
	rpage_file_write(file, &Flag036, 2);
	flag_idx = 37;
	rpage_file_write(file, &flag_idx, 2);
	rpage_file_write(file, &Flag037, 2);
	flag_idx = 38;
	rpage_file_write(file, &flag_idx, 2);
	rpage_file_write(file, &Flag038, 2);
	flag_idx = 39;
	rpage_file_write(file, &flag_idx, 2);
	rpage_file_write(file, &Flag039, 2);
	flag_idx = 40;
	rpage_file_write(file, &flag_idx, 2);
	rpage_file_write(file, &Flag040, 2);
	flag_idx = 41;
	rpage_file_write(file, &flag_idx, 2);
	rpage_file_write(file, &Flag041, 2);
	flag_idx = 42;
	rpage_file_write(file, &flag_idx, 2);
	rpage_file_write(file, &Flag042, 2);
	flag_idx = 68;
	rpage_file_write(file, &flag_idx, 2);
	rpage_file_write(file, &Flag068, 2);
	flag_idx = 69;
	rpage_file_write(file, &flag_idx, 2);
	rpage_file_write(file, &Flag069, 2);
}

void worldResetSpritesState(void)
{
	short i;
	for(i = 0; i < 3; i++) {
		world_sprites[i].enabled = world_sprites[i].enabled_default;
	}
}

void worldSaveSpritesState(rpage_file file)
{
	unsigned short us;
	short len;
	USHORT b;

	char *file_header = SAVE_HEADER_SPRITES;
	rpage_file_write(file, file_header, 4);
	len = 3;
	rpage_file_write(file, &len, 2);

	us = 0xc49f;
	rpage_file_write(file, &us, 2);
	b = (USHORT)world_sprites[0].enabled;	/* go_CABLE */
	rpage_file_write(file, &b, 2);

	us = 0xac05;
	rpage_file_write(file, &us, 2);
	b = (USHORT)world_sprites[1].enabled;	/* go_COMBINE */
	rpage_file_write(file, &b, 2);

	us = 0x7163;
	rpage_file_write(file, &us, 2);
	b = (USHORT)world_sprites[2].enabled;	/* go_TELEPHONE */
	rpage_file_write(file, &b, 2);
}


void gameSaveSlot(short slot, BOOL is_on_hdd)
{
	rpage_file file;
	char *file_header = SAVE_HEADER;
	char filename[16];
	if (is_on_hdd)
		sprintf(filename, "save.%03d", slot);
	else
		sprintf(filename, "%ssave.%03d", SAVE_DISK_NAME, slot);
	// Does the file exists ?
	file = rpage_file_open(filename, MODE_OPEN_FILE);
	if (!file)
		file = rpage_file_open(filename, MODE_CREATE_FILE);
	rpage_file_write(file, file_header, 4);
	game_save_time(file);
	gameSaveWorldState(file);
	gameSaveInventoryState(file);
	worldSaveScenarioFlags(file);
	worldSaveSpritesState(file);
	gameSaveRoomLinks(file);
	gameSavePuzzles(file);
	rpage_file_close(file);
}

void worldLoadScenarioFlags(rpage_file file)
{
	char file_header[4];
	USHORT block_len = 35;
	USHORT flag_idx;

	rpage_file_read(file, &file_header, 4);

	while(block_len--)
	{
		rpage_file_read(file, &flag_idx, 2);
		switch(flag_idx)
		{
			case 1:
				rpage_file_read(file, &Flag001, 2);
				break;
			case 2:
				rpage_file_read(file, &Flag002, 2);
				break;
			case 3:
				rpage_file_read(file, &Flag003, 2);
				break;
			case 4:
				rpage_file_read(file, &Flag004, 2);
				break;
			case 5:
				rpage_file_read(file, &Flag005, 2);
				break;
			case 6:
				rpage_file_read(file, &Flag006, 2);
				break;
			case 7:
				rpage_file_read(file, &Flag007, 2);
				break;
			case 9:
				rpage_file_read(file, &Flag009, 2);
				break;
			case 11:
				rpage_file_read(file, &Flag011, 2);
				break;
			case 12:
				rpage_file_read(file, &Flag012, 2);
				break;
			case 14:
				rpage_file_read(file, &Flag014, 2);
				break;
			case 15:
				rpage_file_read(file, &Flag015, 2);
				break;
			case 17:
				rpage_file_read(file, &Flag017, 2);
				break;
			case 18:
				rpage_file_read(file, &Flag018, 2);
				break;
			case 19:
				rpage_file_read(file, &Flag019, 2);
				break;
			case 20:
				rpage_file_read(file, &Flag020, 2);
				break;
			case 21:
				rpage_file_read(file, &Flag021, 2);
				break;
			case 22:
				rpage_file_read(file, &Flag022, 2);
				break;
			case 23:
				rpage_file_read(file, &Flag023, 2);
				break;
			case 24:
				rpage_file_read(file, &Flag024, 2);
				break;
			case 28:
				rpage_file_read(file, &Flag028, 2);
				break;
			case 29:
				rpage_file_read(file, &Flag029, 2);
				break;
			case 30:
				rpage_file_read(file, &Flag030, 2);
				break;
			case 31:
				rpage_file_read(file, &Flag031, 2);
				break;
			case 32:
				rpage_file_read(file, &Flag032, 2);
				break;
			case 34:
				rpage_file_read(file, &Flag034, 2);
				break;
			case 36:
				rpage_file_read(file, &Flag036, 2);
				break;
			case 37:
				rpage_file_read(file, &Flag037, 2);
				break;
			case 38:
				rpage_file_read(file, &Flag038, 2);
				break;
			case 39:
				rpage_file_read(file, &Flag039, 2);
				break;
			case 40:
				rpage_file_read(file, &Flag040, 2);
				break;
			case 41:
				rpage_file_read(file, &Flag041, 2);
				break;
			case 42:
				rpage_file_read(file, &Flag042, 2);
				break;
			case 68:
				rpage_file_read(file, &Flag068, 2);
				break;
			case 69:
				rpage_file_read(file, &Flag069, 2);
				break;
		}
	}
}

void worldLoadSpritesState(rpage_file file)
{
	char file_header[4];
	short block_len, go_idx;
	USHORT us;
	USHORT b;

	rpage_file_read(file, &file_header, 4);
	rpage_file_read(file, &block_len, 2);

	while(block_len--)
	{
		rpage_file_read(file, &us, 2);
		rpage_file_read(file, &b, 2);
		go_idx = worldGetGameObjectFromCRC16(us);
		world_sprites[go_to_sprite[go_idx]].enabled = (BOOL)b;
	}
}

void gameLoadSlot(short slot, BOOL is_on_hdd)
{
	rpage_file file;
	char file_header[4];
	char filename[16];
	if (is_on_hdd)
		sprintf(filename, "save.%03d", slot);
	else
		sprintf(filename, "%ssave.%03d", SAVE_DISK_NAME, slot);
	file = rpage_file_open(filename, MODE_OPEN_FILE);
	rpage_file_read(file, &file_header, 4);
	game_load_time(file);
	gameLoadWorldState(file);
	gameLoadInventoryState(file);
	worldLoadScenarioFlags(file);
	worldResetSpritesState();
	worldLoadSpritesState(file);
	gameLoadRoomLinks(file);
	gameLoadPuzzles(file);
	rpage_file_close(file);
}

