/* Windless Bay for Amiga OCS -- (c) RESISTANCE.NO 2021 */
/* THIS CODE WAS GENERATED BY R-PAGE RESOURCE TOOLCHAIN */
/*                   DON'T MODIFY IT !                  */

#ifndef _FILE_CONFIG_
#define _FILE_CONFIG_

#define MAX_PAK_SIZE 19840 /* Maximum size (in byte) of a compressed file */
#define MAX_SFX_SIZE 16 /* Maximum size of a 8bit mono audio sample */ 
#endif

