/* Windless Bay for Amiga OCS -- (c) RESISTANCE.NO 2021 */
/* THIS CODE WAS GENERATED BY R-PAGE RESOURCE TOOLCHAIN */
/*                   DON'T MODIFY IT !                  */

#ifndef _FILES_LOCATION_
#define _FILES_LOCATION_

#include <exec/types.h>

typedef struct {
	char *filename;
	UBYTE disk;
} file_dispatch;

#define DATA_DISK_ANY 0
#define DATA_DISK_0 (1 << 0) /* wind1: */
#define DATA_DISK_MAX 1

#define DISK_NAME_0 "wind1:"

#define FILE_DISPATCH_LIST_SIZE 40
extern file_dispatch file_dispatch_list[FILE_DISPATCH_LIST_SIZE];

#endif

