/* Athanor2 (C) Eric "Atlantis" Safar / Safargames 2021 */
/* THIS CODE WAS GENERATED BY R-PAGE RESOURCE TOOLCHAIN */
/*                   DON'T MODIFY IT !                  */

#ifndef _FILES_LOCATION_
#define _FILES_LOCATION_

#include <exec/types.h>

typedef struct {
	char *filename;
	UBYTE disk;
} file_dispatch;

#define DATA_DISK_ANY 0
#define DATA_DISK_0 (1 << 0) /* Ath1: */
#define DATA_DISK_1 (1 << 1) /* Ath2: */
#define DATA_DISK_2 (1 << 2) /* Ath3: */
#define DATA_DISK_MAX 3

#define DISK_NAME_0 "Ath1:"
#define DISK_NAME_1 "Ath2:"
#define DISK_NAME_2 "Ath3:"

#define FILE_DISPATCH_LIST_SIZE 143
extern file_dispatch file_dispatch_list[FILE_DISPATCH_LIST_SIZE];

#endif

