/* Athanor2 (C) Eric "Atlantis" Safar / Safargames 2021 */
/* THIS CODE WAS GENERATED BY R-PAGE RESOURCE TOOLCHAIN */
/*                   DON'T MODIFY IT !                  */

#include "game/aos/files.h"


/* file dispatch */
file_dispatch file_dispatch_list[FILE_DISPATCH_LIST_SIZE] = {
	{ "default", DATA_DISK_0 },
	{ "txt_dialog_fr.pak", DATA_DISK_0 },
	{ "txt_system_fr.pak", DATA_DISK_0 },
	{ "txt_tooltip_fr.pak", DATA_DISK_0 },
	{ "txt_credits_fr.pak", DATA_DISK_0 },
	{ "txt_dialog_en.pak", DATA_DISK_0 },
	{ "txt_system_en.pak", DATA_DISK_0 },
	{ "txt_tooltip_en.pak", DATA_DISK_0 },
	{ "txt_credits_en.pak", DATA_DISK_0 },
	{ "txt_dialog_es.pak", DATA_DISK_0 },
	{ "txt_system_es.pak", DATA_DISK_0 },
	{ "txt_tooltip_es.pak", DATA_DISK_0 },
	{ "txt_credits_es.pak", DATA_DISK_0 },
	{ "gui.pak", DATA_DISK_0 },
	{ "gui_compass_hilite.pak", DATA_DISK_0 },
	{ "gui_compass_hilite_mask.pak", DATA_DISK_0 },
	{ "icons.pak", DATA_DISK_0 },
	{ "inventory_panel.pak", DATA_DISK_0 },
	{ "travel_menu.pak", DATA_DISK_0 },
	{ "spr_inventory.pak", DATA_DISK_0 },
	{ "spr_inventory_mask.pak", DATA_DISK_0 },
	{ "vue_01.pak", DATA_DISK_0 },
	{ "vue_02.pak", DATA_DISK_0 },
	{ "vue_03.pak", DATA_DISK_0 },
	{ "vue_04.pak", DATA_DISK_0 },
	{ "vue_05.pak", DATA_DISK_0 },
	{ "vue_06.pak", DATA_DISK_0 },
	{ "vue_07.pak", DATA_DISK_0 },
	{ "vue_08.pak", DATA_DISK_0 },
	{ "vue_09.pak", DATA_DISK_0 },
	{ "vue_10.pak", DATA_DISK_0 },
	{ "vue_11.pak", DATA_DISK_0 },
	{ "vue_12.pak", DATA_DISK_0 },
	{ "vue_13.pak", DATA_DISK_0 },
	{ "vue_14.pak", DATA_DISK_0 },
	{ "vue_15.pak", DATA_DISK_0 },
	{ "vue_16.pak", DATA_DISK_0 },
	{ "vue_17.pak", DATA_DISK_0 },
	{ "vue_18.pak", DATA_DISK_0 },
	{ "vue_19.pak", DATA_DISK_0 },
};

